In [2]:
# import di moduli esterni:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
A = np.eye(4)
print("tipo di A: ",type(A))
print(A)

tipo di A:  <class 'numpy.ndarray'>
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
# alcuni costruttori di array definiti in numpy:
v = np.array([1, 2, 3])
print(v)
M = np.array([[2, 4],[5, 1]])
print(M)
M2 = np.random.rand(3,3)
print(M2)
vmd = np.ones((2,2,2,2))
print(vmd)
zm = np.zeros((3,2))
print(zm)
D = np.diag(v)
print("D = ",D)
print(np.diag(D))

[1 2 3]
[[2 4]
 [5 1]]
[[0.8215493  0.00480021 0.54736397]
 [0.0011447  0.82515207 0.00125319]
 [0.79138628 0.2031487  0.95943661]]
[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
D =  [[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 2 3]


In [8]:
vmd[0,0,0:1+1,0]

array([1., 1.])

In [9]:
#help(np.random)

In [10]:
# come faccio a sapere il tipo di dato associato alla variabile ?
type(M)

numpy.ndarray

In [11]:
# se gli operandi sono dei vettori, come si comportano gli operatori ?
a = 1.0
# "+" o "-":
print(a + a)
print(v + v)
print(M + M)
print(M + M)
# "*":
print(a * a)
print(v * v)
print("M * M = ",M * M)  # prodotto per componenti
print("M @ M = ",M @ M)  # prodotto matriciale
# "/":
print(a / a)
print(v / v)
print(M / M)


2.0
[2 4 6]
[[ 4  8]
 [10  2]]
[[ 4  8]
 [10  2]]
1.0
[1 4 9]
M * M =  [[ 4 16]
 [25  1]]
M @ M =  [[24 12]
 [15 21]]
1.0
[1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [5]:
# slicing, squeeze, reshape, ...
print(M[:,0])
v = np.atleast_2d(M[:,0]).T
print("v = ",v)
print(M[0,:])
print(np.squeeze(np.asarray(M[0,:])))
print("M dimensions = ",M.shape)
print(np.reshape(M,(M.shape[0]*M.shape[1])))

[2 5]
v =  [[2]
 [5]]
[2 4]
[2 4]
M dimensions =  (2, 2)
[2 4 5 1]


In [13]:
print(vmd.shape)

(2, 2, 2, 2)


In [6]:
v = M[:,1]

In [7]:
print(v)

[4 1]


In [8]:
type(v)

numpy.ndarray

In [9]:
print(np.atleast_2d(v).T) 

[[4]
 [1]]


In [10]:
v = np.atleast_2d(v).T
v.T @ v

array([[17]])

In [11]:
v @ v.T

array([[16,  4],
       [ 4,  1]])